### ISSUE TITLE
Readme.md refers to a "replace" function that is not present

### ISSUE THREAD

**Issue by giorgiofran** [QuiverDart/quiver_strings#13]
In the readme.md file, it is listed a function `repeat` that does not exist in the package.

**Comment by cbracken** [comment]
Can you point me to the line in [README.md](https://github.com/QuiverDart/quiver_strings/blame/master/README.md)? A search for the word `replace` doesn't show any results for me.

**Comment by cbracken** [comment]
Ah maybe you mean `repeat`? I'll delete that. Quiver's been around since pre-Dart 1.0 before `String` added `operator*`.

Now, repeating a string is as simple as:
```dart
String tomsDinerIntro = 'do ' * 16;
```

Thanks for filing the bug!

**Comment by giorgiofran** [comment]
Sorry, it was repeat, not replace ...

**Comment by cbracken** [comment]
Awesome - fixed in #15. Fixed in the combined package in google/quiver-dart#363. Thanks for reporting this!
